---
- name: Make sure pip package installed.
  apt:
    name: python3-pip
    state: present

- name: Install docker package.
  ansible.builtin.pip:
    name: docker>=5.0.0
    state: present

- name: Install jsondiff package.
  ansible.builtin.pip:
    name: jsondiff
    state: present